[config]
default_to_workspace = false

[tasks.default]
alias = "build"

[tasks.build]
dependencies = ["npm-build", "cargo-build"]

[tasks.clean]
dependencies = ["cargo-clean", "npm-clean"]

[tasks.dev]
run_task ={ name = ["cargo-run", "npm-dev"], parallel = true }

[tasks.install]
run_task ={ name = ["cargo-install", "npm-install"], parallel = true }

[tasks.cargo-run]
command = "cargo"
args = ["watch", "-x", "run", "-w", "src", "-w", "lib", "-w", "Cargo.toml"]

[tasks.cargo-clean]
command = "cargo"
args = ["clean"]

[tasks.cargo-install]
command = "cargo"
args = ["check"]

[tasks.cargo-build]
command = "cargo"
args = ["build", "--release"]

[tasks.npm-clean]
command = "npm"
args = ["--prefix", "ui/", "run", "clean"]

[tasks.npm-install]
command = "npm"
args = ["--prefix", "ui/", "install"]

[tasks.npm-build]
command = "npm"
args = ["--prefix", "ui/", "run", "build"]

[tasks.npm-dev]
command = "npm"
args = ["--prefix", "ui/", "run", "dev"]